apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: podvolumebackup-list
spec:
  version: "v0.0.1"
  homepage: https://github.com/Digitalist-Open-Cloud/krew-podvolumebackup-list
  shortDescription: List Velero podvolumebackups with size, pod and date
  description: |
    A simple plugin to list Velero podvolumebackups for a given backup prefix, showing pod name, volume, size and creation date.
    Requires jq and numfmt installed locally.
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    uri: https://github.com/Digitalist-Open-Cloud/krew-podvolumebackup-list/releases/download/v0.0.1/kubectl-podvolumebackup-list
    sha256: 626e449316cf59dfbafbf612d3894ed5564d17ebbc5ceb6dce47ab41bdc0507b
    bin: kubectl-podvolumebackup-list
    files:
      - from: kubectl-podvolumebackup-list
        to: .
  caveats: |
    This plugin requires 'jq' and 'numfmt' installed and available in your PATH.
    Usage:
      kubectl podvolumebackup-list <backup name prefix> [namespace]