apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: podvolumebackup-list
spec:
  version: "v0.0.2"
  homepage: https://github.com/Digitalist-Open-Cloud/krew-podvolumebackup-list
  shortDescription: List Velero podvolumebackups with size, pod and date
  description: |
    A simple plugin to list Velero podvolumebackups for a given backup prefix, showing pod name, volume, size and creation date.
    Requires jq and numfmt installed locally.
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    uri: https://github.com/Digitalist-Open-Cloud/krew-podvolumebackup-list/releases/download/v0.0.1/kubectl-podvolumebackup_list
    sha256: eab8d9ff1564fd778a3847ac0b8c57f3f37991169aae37efebfe93ab738a9afe
    bin: kubectl-podvolumebackup_list
    files:
      - from: kubectl-podvolumebackup_list
        to: .
  caveats: |
    This plugin requires 'jq' and 'numfmt' installed and available in your PATH.
    Usage:
      kubectl podvolumebackup-list <backup name prefix> [namespace]