name: Release Krew plugin (Go)
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Set variables
        id: vars
        run: |
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "REPO=${{ github.repository }}" >> $GITHUB_ENV

      - name: Build and package (linux, darwin, windows)
        run: |
          set -euo pipefail

          BASENAME="kubectl-podvolumebackup-list"
          mkdir -p dist

          build_nix () {
            GOOS="$1"; GOARCH="$2"
            OUTBIN="$BASENAME"
            ARCHIVE="podvolumebackup-list_${GOOS}_${GOARCH}.tar.gz"

            echo "==> Building $GOOS/$GOARCH"
            rm -f "$OUTBIN"
            CGO_ENABLED=0 GOOS="$GOOS" GOARCH="$GOARCH" go build -trimpath -ldflags="-s -w" -o "$OUTBIN" .

            echo "==> Packaging $ARCHIVE"
            tar -czf "dist/$ARCHIVE" "$OUTBIN"
            rm -f "$OUTBIN"

            SHA=$(sha256sum "dist/$ARCHIVE" | awk '{print $1}')
            VAR="SHA_$(echo $GOOS | tr '[:lower:]' '[:upper:]')_$(echo $GOARCH | tr '[:lower:]' '[:upper:]')"
            echo "$VAR=$SHA" >> $GITHUB_ENV
          }

          build_win () {
            GOARCH="$1"
            OUTBIN="${BASENAME}.exe"
            ARCHIVE="podvolumebackup-list_windows_${GOARCH}.zip"

            echo "==> Building windows/${GOARCH}"
            rm -f "$OUTBIN"
            CGO_ENABLED=0 GOOS=windows GOARCH="$GOARCH" go build -trimpath -ldflags="-s -w" -o "$OUTBIN" .

            echo "==> Packaging $ARCHIVE"
            (cd . && zip -q "dist/$ARCHIVE" "$OUTBIN")
            rm -f "$OUTBIN"

            SHA=$(sha256sum "dist/$ARCHIVE" | awk '{print $1}')
            VAR="SHA_WINDOWS_$(echo $GOARCH | tr '[:lower:]' '[:upper:]')"
            echo "$VAR=$SHA" >> $GITHUB_ENV
          }

          # Linux
          build_nix linux amd64
          build_nix linux arm64

          # macOS
          build_nix darwin amd64
          build_nix darwin arm64

          # Windows
          build_win amd64
          build_win arm64

      - name: Generate Krew manifest
        run: |
          cat > dist/podvolumebackup-list.yaml <<EOF
          apiVersion: krew.googlecontainertools.github.com/v1alpha2
          kind: Plugin
          metadata:
            name: podvolumebackup-list
          spec:
            version: "${TAG}"
            homepage: https://github.com/${REPO}
            shortDescription: List Velero PodVolumeBackups with filters and multiple output formats
            description: |
              A kubectl plugin to list Velero PodVolumeBackups with filters for backup prefix, pod name, pod namespace, and volume.
              Outputs as table (default), JSON, YAML or CSV. Shows size (totalBytes/bytesDone), pod, namespace, volume and timestamps.
            platforms:
            - selector:
                matchLabels:
                  os: linux
                  arch: amd64
              uri: https://github.com/${REPO}/releases/download/${TAG}/podvolumebackup-list_linux_amd64.tar.gz
              sha256: ${SHA_LINUX_AMD64}
              bin: kubectl-podvolumebackup-list
              files:
                - from: kubectl-podvolumebackup-list
                  to: .
            - selector:
                matchLabels:
                  os: linux
                  arch: arm64
              uri: https://github.com/${REPO}/releases/download/${TAG}/podvolumebackup-list_linux_arm64.tar.gz
              sha256: ${SHA_LINUX_ARM64}
              bin: kubectl-podvolumebackup-list
              files:
                - from: kubectl-podvolumebackup-list
                  to: .
            - selector:
                matchLabels:
                  os: darwin
                  arch: amd64
              uri: https://github.com/${REPO}/releases/download/${TAG}/podvolumebackup-list_darwin_amd64.tar.gz
              sha256: ${SHA_DARWIN_AMD64}
              bin: kubectl-podvolumebackup-list
              files:
                - from: kubectl-podvolumebackup-list
                  to: .
            - selector:
                matchLabels:
                  os: darwin
                  arch: arm64
              uri: https://github.com/${REPO}/releases/download/${TAG}/podvolumebackup-list_darwin_arm64.tar.gz
              sha256: ${SHA_DARWIN_ARM64}
              bin: kubectl-podvolumebackup-list
              files:
                - from: kubectl-podvolumebackup-list
                  to: .
            - selector:
                matchLabels:
                  os: windows
                  arch: amd64
              uri: https://github.com/${REPO}/releases/download/${TAG}/podvolumebackup-list_windows_amd64.zip
              sha256: ${SHA_WINDOWS_AMD64}
              bin: kubectl-podvolumebackup-list.exe
              files:
                - from: kubectl-podvolumebackup-list.exe
                  to: .
            - selector:
                matchLabels:
                  os: windows
                  arch: arm64
              uri: https://github.com/${REPO}/releases/download/${TAG}/podvolumebackup-list_windows_arm64.zip
              sha256: ${SHA_WINDOWS_ARM64}
              bin: kubectl-podvolumebackup-list.exe
              files:
                - from: kubectl-podvolumebackup-list.exe
                  to: .
          EOF

      - name: Prepare release notes
        run: |
          {
            echo "## How to install the plugin with Krew"
            echo
            echo "Download the manifest from this release and install:"
            echo '```bash'
            echo "curl -LO https://github.com/${REPO}/releases/download/${TAG}/podvolumebackup-list.yaml"
            echo "kubectl krew install --manifest=podvolumebackup-list.yaml"
            echo "rm podvolumebackup-list.yaml"
            echo '```'
            echo
            echo "Binaries & checksums are attached to this release."
          } > dist/RELEASE_NOTES.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: dist/RELEASE_NOTES.md
          files: |
            dist/podvolumebackup-list_linux_amd64.tar.gz
            dist/podvolumebackup-list_linux_arm64.tar.gz
            dist/podvolumebackup-list_darwin_amd64.tar.gz
            dist/podvolumebackup-list_darwin_arm64.tar.gz
            dist/podvolumebackup-list_windows_amd64.zip
            dist/podvolumebackup-list_windows_arm64.zip
            dist/podvolumebackup-list.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}