name: Create release for Krew plugin

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write    # <-- required to let the token create releases

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set variables (version, URI)
        id: vars
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "tag_name=$TAG" >> $GITHUB_OUTPUT
          echo "uri=https://github.com/${GITHUB_REPOSITORY}/releases/download/$TAG/kubectl-podvolumebackup_list" >> $GITHUB_OUTPUT

      - name: Make sure plugin is executable
        run: chmod +x kubectl-podvolumebackup_list

      - name: Create plugin archive
        run: tar -czf podvolumebackup-list.tar.gz kubectl-podvolumebackup_list

      - name: Generate SHA256 checksum
        id: checksum
        run: |
          sha256sum podvolumebackup-list.tar.gz | awk '{print $1}' > plugin.sha256
          echo "sha256=$(cat plugin.sha256)" >> $GITHUB_OUTPUT

      - name: Generate Krew manifest (linux + mac)
        run: |
          cat <<EOF > podvolumebackup-list.yaml
          apiVersion: krew.googlecontainertools.github.com/v1alpha2
          kind: Plugin
          metadata:
            name: podvolumebackup-list
          spec:
            version: "${{ steps.vars.outputs.tag_name }}"
            homepage: https://github.com/${{ github.repository }}
            shortDescription: List Velero podvolumebackups with size, pod and date
            description: |
              A kubectl plugin to list Velero podvolumebackups for a given prefix, with fields for pod, volume, size and creation date.
              Requires jq and numfmt installed locally.
            platforms:
            - selector:
                matchLabels:
                  os: linux
                  arch: amd64
              uri: https://github.com/${{ github.repository }}/releases/download/${{ steps.vars.outputs.tag_name }}/podvolumebackup-list.tar.gz
              sha256: ${{ steps.checksum.outputs.sha256 }}
              bin: kubectl-podvolumebackup_list
              files:
                - from: kubectl-podvolumebackup_list
                  to: .
            - selector:
                matchLabels:
                  os: darwin
                  arch: arm64
              uri: https://github.com/${{ github.repository }}/releases/download/${{ steps.vars.outputs.tag_name }}/podvolumebackup-list.tar.gz
              sha256: ${{ steps.checksum.outputs.sha256 }}
              bin: kubectl-podvolumebackup_list
              files:
                - from: kubectl-podvolumebackup_list
                  to: .
            caveats: |
              This plugin requires 'jq' and 'numfmt' installed and available in your PATH.
              Usage:
                kubectl podvolumebackup-list <backup name prefix> [namespace]
          EOF

      - name: Prepare release notes
        id: notes
        run: |
          {
            echo "## How to install the plugin with Krew"
            echo ""
            echo "You can install this version directly with Krew using the manifest from this release:"
            echo ""
            echo '```bash'
            echo "kubectl krew install --manifest=https://github.com/${{ github.repository }}/releases/download/${{ steps.vars.outputs.tag_name }}/podvolumebackup-list.yaml"
            echo '```'
            echo ""
            echo "Or download manually:"
            echo ""
            echo " - Script: [kubectl-podvolumebackup_list](${{ steps.vars.outputs.uri }})"
            echo " - Manifest: [podvolumebackup-list.yaml](https://github.com/${{ github.repository }}/releases/download/${{ steps.vars.outputs.tag_name }}/podvolumebackup-list.yaml)"
            echo ""
            echo "SHA256: \`${{ steps.checksum.outputs.sha256 }}\`"
          } > RELEASE_NOTES.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: RELEASE_NOTES.md
          files: |
            kubectl-podvolumebackup_list
            plugin.sha256
            podvolumebackup-list.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}